In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import (
    StandardScaler,
    MinMaxScaler,
    LabelEncoder,
    OrdinalEncoder
)

In [2]:
df = pd.read_csv("Titanic-Dataset.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.shape

(891, 12)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [5]:
df.describe(include="all")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [6]:
print("Target Variable")
df["Survived"].value_counts()

Target Variable

Survived
0    549
1    342
Name: count, dtype: int64

In [7]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
df["Age"] = df["Age"].fillna(df["Age"].median())

df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

df["Cabin"] = df["Cabin"].fillna("Unknown")

In [9]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [10]:
print(df.duplicated().sum())

0

In [11]:
df = df.drop_duplicates()

In [12]:
numerical_columns = ["Age","Fare","SibSp","Parch"]

for column in numerical_columns:

    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5*IQR
    upper = Q3 + 1.5*IQR

    outliers = df[(df[column] < lower) | (df[column] > upper)]

    print(column, len(outliers))

Age 66
Fare 116
SibSp 46
Parch 213

In [13]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [14]:
label = LabelEncoder()

df["Sex"] = label.fit_transform(df["Sex"])

In [15]:
df = pd.get_dummies(
    df,
    columns=["Embarked"],
    drop_first=True
)

In [16]:
encoder = OrdinalEncoder(
    categories=[[1,2,3]]
)

df[["Pclass"]] = encoder.fit_transform(df[["Pclass"]])

In [17]:
scaler = StandardScaler()

columns = ["Age","Fare","SibSp","Parch"]

df[columns] = scaler.fit_transform(df[columns])

In [18]:
df = df.drop(
    columns=[
        "PassengerId",
        "Name",
        "Ticket",
        "Cabin"
    ]
)

df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_Q,Embarked_S
0,0,2.0,1,-0.565736,0.432793,-0.473674,-0.502445,False,True
1,1,0.0,0,0.663861,0.432793,-0.473674,0.786845,False,False
2,1,2.0,0,-0.258337,-0.474545,-0.473674,-0.488854,False,True
3,1,0.0,0,0.433312,0.432793,-0.473674,0.420730,False,True
4,0,2.0,1,0.433312,-0.474545,-0.473674,-0.486337,False,True

In [19]:
df.skew(numeric_only=True)

Survived      0.478523
Pclass       -0.630548
Sex          -0.618921
Age           0.510245
SibSp         3.695352
Parch         2.749117
Fare          4.787317
Embarked_Q    2.948778
Embarked_S   -1.009665
dtype: float64

In [20]:
df["Fare"] = np.log1p(df["Fare"] - df["Fare"].min() + 1)

In [21]:
df.skew(numeric_only=True)

Survived      0.478523
Pclass       -0.630548
Sex          -0.618921
Age           0.510245
SibSp         3.695352
Parch         2.749117
Fare          2.507412
Embarked_Q    2.948778
Embarked_S   -1.009665
dtype: float64

In [22]:
df.to_csv(
    "Titanic_Cleaned.csv",
    index=False
)

print("Dataset Saved Successfully")

Dataset Saved Successfully